quarkus.application.name=gdpbff
quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${GDP_DB_USER}
quarkus.datasource.password=${GDP_DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://gdp-db.prod.csi.it:5432/gdp_db
quarkus.hibernate-orm.database.generation=none

# Auth / JWT (from info)
quarkus.smallrye-jwt.enabled=true

# Orchestrator API Client
gdporch.api.url=http://gdporch-service:8082
quarkus.rest-client."it.csipiemonte.gdp.gdpbff.client.OrchClient".url=${gdporch.api.url}

# DAM LIBRA REST Client
libra.api.url=http://ts-libra-sv-exp1.csi.it/rpcr02
quarkus.rest-client."it.csipiemonte.gdp.gdpbff.client.LibreClient".url=${libra.api.url}

# Monitoring settings
quarkus.micrometer.export.prometheus.enabled=true
quarkus.smallrye-health.root-path=/q/health
