services:
  postgres:
    image: postgres:15-alpine
    container_name: gdp-db
    environment:
      POSTGRES_DB: gdp_db
      POSTGRES_USER: gdp_user
      POSTGRES_PASSWORD: gdp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/scripts/populate_db.sql:/docker-entrypoint-initdb.d/02_populate_db.sql
    networks:
      - gdp-network

  sftp:
    image: atmoz/sftp:alpine
    container_name: gdp-sftp
    environment:
      - SFTP_USERS=tester:password:1001:1001:flusso_regolare,flusso_saltuario,_tmp,_dam,_errata
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data:/home/tester
    networks:
      - gdp-network

volumes:
  postgres_data:

networks:
  gdp-network:
    driver: bridge
