/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created" ON : 19-mar-2026 15:55:15 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS GDP_CODA_CARICAMENTO CASCADE;

DROP TABLE IF EXISTS GDP_DATA_USCITA CASCADE;

DROP TABLE IF EXISTS GDP_EDIZIONE CASCADE;

DROP TABLE IF EXISTS GDP_FASCICOLO CASCADE;

DROP TABLE IF EXISTS GDP_FASCICOLO_PAG CASCADE;

DROP TABLE IF EXISTS GDP_LOG CASCADE;

DROP TABLE IF EXISTS GDP_LOG_EDIZIONE CASCADE;

DROP TABLE IF EXISTS GDP_MAIL CASCADE;

DROP TABLE IF EXISTS GDP_PAGINA CASCADE;

DROP TABLE IF EXISTS GDP_PERIODICITA CASCADE;

DROP TABLE IF EXISTS GDP_PREF_EDIZIONE CASCADE;

DROP TABLE IF EXISTS GDP_PREF_TESTATA CASCADE;

DROP TABLE IF EXISTS GDP_PROVINCE CASCADE;

DROP TABLE IF EXISTS GDP_TEMA CASCADE;

DROP TABLE IF EXISTS GDP_TESTATA CASCADE;

DROP TABLE IF EXISTS GDP_TIPO_EDIZIONE CASCADE;

DROP TABLE IF EXISTS GDP_TIPO_FILE CASCADE;

DROP TABLE IF EXISTS GDP_UTENTESFTP CASCADE;

DROP TABLE IF EXISTS GDP_UTENTEWEB CASCADE;

/* Create Tables */

CREATE TABLE GDP_CODA_CARICAMENTO
(
	ID_GDP_CODA_CARICAMENTO integer NOT NULL,
	DT_INSERIM_IN_CODA date NOT NULL,
	FK_GDP_LOG_EDIZIONE integer NOT NULL,
	NRO_TENTATIVO integer NOT NULL   DEFAULT 0,
	DT_TENTATIVO timestamp without time zone NULL,
	SFTP_PATH varchar(256) NOT NULL,
	PRIORITA integer NULL,
	STATO varchar(64) NULL,
	NRO_MAX_TENTATIVI integer NULL   DEFAULT 10
);

CREATE TABLE GDP_DATA_USCITA
(
	ID_GDP_DATA_USCITA integer NOT NULL,
	FK_GDP_PERIODICITA integer NOT NULL,
	DT_INIZIO date NOT NULL,
	DT_FINE date NOT NULL,
	DATA_ATTESA date NOT NULL,
	SOSPESA boolean NOT NULL   DEFAULT False
);

CREATE TABLE GDP_EDIZIONE
(
	ID_GDP_EDIZIONE integer NOT NULL,
	FK_GDP_TESTATA integer NOT NULL,
	DATA_EDIZIONE date NOT NULL,	-- è la data di uscita in edicola dell’edizione
	DATA_PUBBLICAZIONE date NOT NULL,	--   >  per le edizioni attive è valorizzata con la data in cui diverrà visibile a tutti   >  per le edizioni storiche è uguale alla data edizione
	STATO integer NULL,
	TOTALE_PAGINE integer NOT NULL
);

CREATE TABLE GDP_FASCICOLO
(
	ID_GDP_FASCICOLO integer NOT NULL,
	FK_GDP_UTENTEWEB integer NOT NULL,
	TITOLO varchar(128) NULL,
	NOTE_FASCICOLO varchar(512) NULL,	-- Note inserite dall'utente sul fascicolo
	DT_MODIFICA date NULL,
	DT_ELIMINAZIONE date NULL
);

CREATE TABLE GDP_FASCICOLO_PAG
(
	ID_GDP_FASCICOLO_PAG integer NOT NULL,
	FK_GDP_FASCICOLO integer NOT NULL,
	FK_GDP_PAGINA integer NOT NULL,	-- riferimento alla pagina inserita nel fascicolo
	NOTE_PAGINA varchar(512) NULL,	-- Note inserite dall'utente sulla PAGINA
	POSIZIONE integer NOT NULL,	-- Posizione ordinale della pagina all’interno del fascicolo (modificabile dall’utente)
	DT_MODIFICA date NULL,
	DT_ELIMINAZIONE date NULL
);

CREATE TABLE GDP_LOG
(
	ID_GDP_LOG integer NOT NULL,
	FK_GDP_UTENTEFTP integer NOT NULL,
	FK_GDP_TESTATA integer NOT NULL,
	TIPO_ACQUISIZIONE varchar(16) NOT NULL,	-- G = giornaliera S = storica
	DT_ACQUISIZIONE date NOT NULL,	-- E’ la data della trasmissione FTP nel formato yyyy-mm-dd HH:MM:SS ricavata dalla creazione dei file
	TOTALE_FILE_ACQUISITI integer NULL,	-- Totale numero file presenti in area ftp
	ESITO varchar(1024) NULL	-- msg valorizzatI a seguito della chiusura complessiva del processo
);

CREATE TABLE GDP_LOG_EDIZIONE
(
	ID_GDP_LOG_EDIZIONE integer NOT NULL,
	FK_GDP_LOG integer NOT NULL,
	NRO_PAG_ACQUISITE integer NULL,	-- file PDF dell'edizione acquisiti in area ftp
	TIPO_EDIZIONE varchar(64) NULL,	-- decodificato su GDP_TIPO_EDIZIONE
	FK_GDP_EDIZIONE integer NOT NULL,
	PATH_EDIZIONE varchar(256) NULL,
	NRO_PAG_VALIDE integer NULL,	-- file PDF che sono stati correttamente registrati su DB e trasmessi al DAM
	NRO_PAG_ERRATE integer NULL,	-- file PDF che presentano anomalia (non leggibili, nome errato,…)
	PRIMA_PAGINA boolean NULL,	-- Indica se è presente la prima pagina (identificata attraverso il nome del file o proceura euristica)
	FILE_XML boolean NULL,	-- Indica se il file è stato generato
	FILE_ZIP boolean NULL,	-- Indica se il file è stato generato
	JOB_ID varchar(128) NULL,	-- Identificativo dell’operazione attivata sul DAM per il caricamento dell’edizione, restituito dal servizio richiamato
	DESCRIZIONE varchar(8192) NULL	-- Eventuali dettagli su qualsiasi tipo di anomialia rilevata
);

CREATE TABLE GDP_MAIL
(
	COD_MAIL varchar(5) NOT NULL,
	SMTP_MAIL_HOST varchar(128) NOT NULL,
	SMTP_MAIL_PORTA integer NOT NULL,
	MITTENTE varchar(128) NOT NULL,
	TESTO_OGGETTO varchar(1024) NOT NULL,
	TESTO_MAIL varchar(4096) NOT NULL
);

CREATE TABLE GDP_PAGINA
(
	ID_GDP_PAGINA integer NOT NULL,
	FK_GDP_TESTATA integer NOT NULL,
	FK_GDP_EDIZIONE integer NOT NULL,
	NUM_PAGINA integer NOT NULL,
	FILE_PDF varchar(128) NOT NULL,
	FILE_TXT varchar(128) NOT NULL,
	FILE_TIF varchar(128) NULL,
	ANNO_EDIZIONE integer NOT NULL,	-- è l'anno della data di uscita in edicola dell’edizione
	STATO integer NOT NULL,
	OBLIO varchar(256) NULL,	-- Elenco delle voci eventualemente deindicizzare.
	DATA_OBLIO date NULL,	-- Data della richiesta di deindicizzazione
	NOTA_OBLIO varchar(2048) NULL	-- Contiene eventuali informazioni integrative da pubblicare relative a richieste di oblio
);

CREATE TABLE GDP_PERIODICITA
(
	ID_GDP_PERIODICITA integer NOT NULL,
	FK_GDP_TESTATA integer NOT NULL,
	MENSILITA integer NOT NULL,
	GG_PERIODICITA varchar(128) NOT NULL,	-- Regola di calcolo  vedi procedura “F01 - Configurazione date edizioni attese” 
	DT_FINE_VALIDITA date NULL,	-- è la data di fine validità della configurazione di periodicità.  VINCOLO: un solo record con NULL
	INIZIO_SOSPENSIONE date NULL,	-- Se valorizzata deve esserlo anche FINE_SOSPENSIONE. Indicano il periodo nel quale non sono attese edizioni; quindi i corrispondenti record nella tabella DATA_USCITA devono avere SOSPESA = True
	FINE_SOSPENSIONE date NULL	-- Se valorizzata deve esserlo anche INIZIO_SOSPENSIONE. Indicano il periodo nel quale non sono attese edizioni; quindi i corrispondenti record nella tabella DATA_USCITA devono avere SOSPESA = True
);

CREATE TABLE GDP_PREF_EDIZIONE
(
	ID_GDP_PREF_EDIZIONE integer NOT NULL,
	FK_GDP_UTENTEWEB integer NOT NULL,
	FK_GDP_EDIZIONE integer NOT NULL,
	DT_PUBBLICAZIONE date NOT NULL,	-- Campo ridondato di GDP_EDIZIONE
	DT_CREAZIONE date NOT NULL
);

CREATE TABLE GDP_PREF_TESTATA
(
	ID_GDP_PREF_TESTATA integer NOT NULL,
	FK_GDP_UTENTEWEB integer NOT NULL,
	FK_GDP_TESTATA integer NOT NULL,
	NOME_TESTATA varchar(128) NULL,
	DT_CREAZIONE date NOT NULL
);

CREATE TABLE GDP_PROVINCE
(
	SIGLA varchar(2) NOT NULL,
	PROVINCIA varchar(128) NOT NULL
);

CREATE TABLE GDP_TEMA
(
	COD_TEMA integer NOT NULL,
	TEMA varchar(256) NOT NULL
);

CREATE TABLE GDP_TESTATA
(
	ID_GDP_TESTATA integer NOT NULL,
	NOME_TESTATA varchar(256) NOT NULL,
	CARTELLA_TESTATA varchar(256) NULL,
	INVIO_EDIZIONE boolean NOT NULL,	-- True = testate che inviano edizioni pediodiche False = testate che non inviano
	STATO integer NOT NULL,	-- 0 = attiva 1 = storica
	DATA_STATO date NULL,
	CANCELLAZIONE date NULL,
	COD_TEMA integer NOT NULL,
	TEMA varchar(128) NULL,
	SOC_EDITRICE varchar(256) NULL,	-- per le testate in attività con flusso periodico
	ENTE_PROPONENTE varchar(256) NULL,	-- per le testate storiche con caricamenti saltuari Ex PRESENTATO_DA
	ANNO_FONDAZIONE integer NULL,
	PERIODO_FREQ varchar(128) NULL,
	PERIODO_GG varchar(128) NULL,
	DESCRIZIONE varchar(2048) NULL,
	WWW varchar(128) NULL,
	MAIL varchar(128) NULL,
	PROVINCIA varchar(2) NOT NULL,
	COMUNE varchar(128) NULL,
	INDIRIZZO varchar(256) NULL,
	CAP varchar(40) NULL,
	LONGITUDINE numeric(12,9) NULL,
	LATITUDINE numeric(11,9) NULL
);

CREATE TABLE GDP_TIPO_EDIZIONE
(
	COD_TIPO varchar(8) NOT NULL,
	TIPO_EDIZIONE varchar(128) NOT NULL
);

CREATE TABLE GDP_TIPO_FILE
(
	COD_TIPO varchar(8) NOT NULL,
	TIPO_FILE varchar(128) NOT NULL
);

CREATE TABLE GDP_UTENTESFTP
(
	ID_GDP_UTENTESFTP integer NOT NULL,
	USERNAME varchar(128) NOT NULL,
	PASSWORD varchar(128) NOT NULL,
	RIF_TESTATA varchar(128) NULL,
	HOME_SFTP varchar(256) NOT NULL,
	DIRETTORE varchar(50) NULL,
	REFERENTE_SFTP varchar(50) NULL,
	EMAIL varchar(50) NULL,
	WWW varchar(50) NULL,
	EDITORE varchar(50) NULL,
	INDIRIZZO varchar(50) NULL,
	TELEFONO_FISSO varchar(50) NULL,
	TELEFONO_CELLULARE varchar(50) NULL,
	DT_CREAZIONE varchar(50) NULL,
	DT_FINE_VALIDITA varchar(50) NULL,
	STATO varchar(50) NULL
);

CREATE TABLE GDP_UTENTEWEB
(
	ID_GDP_UTENTEWEB integer NOT NULL,
	CODICE_FISCALE varchar(32) NOT NULL,
	COGNOME varchar(64) NULL,
	NOME varchar(64) NULL,
	RUOLO varchar(64) NULL,
	EMAIL varchar(128) NOT NULL,
	DT_CREAZIONE date NOT NULL,
	DT_ANNULLAMENTO date NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE GDP_CODA_CARICAMENTO ADD CONSTRAINT "PK_GDP_CODA_CARICAMENTO"
	PRIMARY KEY (ID_GDP_CODA_CARICAMENTO);

CREATE INDEX "IXFK_GDP_CODA_CARICAMENTO_GDP_LOG_EDIZIONE" ON GDP_CODA_CARICAMENTO (FK_GDP_LOG_EDIZIONE ASC);

ALTER TABLE GDP_DATA_USCITA ADD CONSTRAINT "PK_GDP_DATA_USCITA"
	PRIMARY KEY (ID_GDP_DATA_USCITA);

CREATE INDEX "IXFK_GDP_DATA_USCITA_GDP_PERIODICITA" ON GDP_DATA_USCITA (FK_GDP_PERIODICITA ASC);

ALTER TABLE GDP_EDIZIONE ADD CONSTRAINT "PK_EDIZIONE"
	PRIMARY KEY (ID_GDP_EDIZIONE);

CREATE INDEX "IXFK_GDP_EDIZIONE_GDP_TESTATA" ON GDP_EDIZIONE (FK_GDP_TESTATA ASC);

ALTER TABLE GDP_FASCICOLO ADD CONSTRAINT "PK_GDP_FASCICOLO"
	PRIMARY KEY (ID_GDP_FASCICOLO);

CREATE INDEX "IXFK_GDP_FASCICOLO_GDP_UTENTEWEB" ON GDP_FASCICOLO (FK_GDP_UTENTEWEB ASC);

ALTER TABLE GDP_FASCICOLO_PAG ADD CONSTRAINT "PK_GDP_FASCICOLO_PAG"
	PRIMARY KEY (ID_GDP_FASCICOLO_PAG);

CREATE INDEX "IXFK_GDP_FASCICOLO_PAG_GDP_FASCICOLO" ON GDP_FASCICOLO_PAG (FK_GDP_FASCICOLO ASC);

CREATE INDEX "IXFK_GDP_FASCICOLO_PAG_GDP_PAGINA" ON GDP_FASCICOLO_PAG (FK_GDP_PAGINA ASC);

ALTER TABLE GDP_LOG ADD CONSTRAINT "PK_GDP_LOG"
	PRIMARY KEY (ID_GDP_LOG);

CREATE INDEX "IXFK_GDP_LOG_GDP_TESTATA" ON GDP_LOG (FK_GDP_TESTATA ASC);

CREATE INDEX "IXFK_GDP_LOG_GDP_UTENTESFTP" ON GDP_LOG (FK_GDP_UTENTEFTP ASC);

ALTER TABLE GDP_LOG_EDIZIONE ADD CONSTRAINT "PK_GDP_LOG_EDIZIONE"
	PRIMARY KEY (ID_GDP_LOG_EDIZIONE);

CREATE INDEX "IXFK_GDP_LOG_EDIZIONE_GDP_EDIZIONE" ON GDP_LOG_EDIZIONE (FK_GDP_EDIZIONE ASC);

CREATE INDEX "IXFK_GDP_LOG_EDIZIONE_GDP_LOG" ON GDP_LOG_EDIZIONE (FK_GDP_LOG ASC);

CREATE INDEX "IXFK_GDP_LOG_EDIZIONE_GDP_TIPO_EDIZIONE" ON GDP_LOG_EDIZIONE (TIPO_EDIZIONE ASC);

ALTER TABLE GDP_MAIL ADD CONSTRAINT "PK_GDP_MAIL"
	PRIMARY KEY (COD_MAIL);

ALTER TABLE GDP_PAGINA ADD CONSTRAINT "PK_GDP_PAGINA"
	PRIMARY KEY (ID_GDP_PAGINA);

CREATE INDEX "IXFK_GDP_Pagina_GDP_EDIZIONE" ON GDP_PAGINA (FK_GDP_EDIZIONE ASC);

CREATE INDEX "IXFK_GDP_Pagina_GDP_TESTATA" ON GDP_PAGINA (FK_GDP_TESTATA ASC);

ALTER TABLE GDP_PERIODICITA ADD CONSTRAINT "PK_GDP_PERIODICITA"
	PRIMARY KEY (ID_GDP_PERIODICITA);

CREATE INDEX "IXFK_GDP_PERIODICITA_GDP_TESTATA" ON GDP_PERIODICITA (FK_GDP_TESTATA ASC);

ALTER TABLE GDP_PREF_EDIZIONE ADD CONSTRAINT "PK_GDP_PREF_EDIZIONE"
	PRIMARY KEY (ID_GDP_PREF_EDIZIONE);

CREATE INDEX "IXFK_GDP_PREF_EDIZIONE_GDP_EDIZIONE" ON GDP_PREF_EDIZIONE (FK_GDP_EDIZIONE ASC);

CREATE INDEX "IXFK_GDP_PREF_EDIZIONE_GDP_UTENTEWEB" ON GDP_PREF_EDIZIONE (FK_GDP_UTENTEWEB ASC);

ALTER TABLE GDP_PREF_TESTATA ADD CONSTRAINT "PK_GDP_PREF_TESTATA"
	PRIMARY KEY (ID_GDP_PREF_TESTATA);

CREATE INDEX "IXFK_GDP_PREF_TESTATA_GDP_TESTATA" ON GDP_PREF_TESTATA (FK_GDP_TESTATA ASC);

CREATE INDEX "IXFK_GDP_PREF_TESTATA_GDP_UTENTEWEB" ON GDP_PREF_TESTATA (FK_GDP_UTENTEWEB ASC);

ALTER TABLE GDP_PROVINCE ADD CONSTRAINT "PK_GDP_PROVINCE"
	PRIMARY KEY (SIGLA);

ALTER TABLE GDP_TEMA ADD CONSTRAINT "PK_GDP_TEMA"
	PRIMARY KEY (COD_TEMA);

ALTER TABLE GDP_TESTATA ADD CONSTRAINT "PK_GDP_TESTATA"
	PRIMARY KEY (ID_GDP_TESTATA);

ALTER TABLE GDP_TIPO_EDIZIONE ADD CONSTRAINT "PK_GDP_TIPO_EDIZIONE"
	PRIMARY KEY (COD_TIPO);

ALTER TABLE GDP_TIPO_FILE ADD CONSTRAINT "PK_GDP_TIPO_FILE"
	PRIMARY KEY (COD_TIPO);

ALTER TABLE GDP_UTENTESFTP ADD CONSTRAINT "PK_GDP_UTENTEFTP"
	PRIMARY KEY (ID_GDP_UTENTESFTP);

ALTER TABLE GDP_UTENTEWEB ADD CONSTRAINT "PK_GDP_UTENTEWEB"
	PRIMARY KEY (ID_GDP_UTENTEWEB);

/* Create Foreign Key Constraints */

ALTER TABLE GDP_CODA_CARICAMENTO ADD CONSTRAINT "FK_GDP_CODA_CARICAMENTO_GDP_LOG_EDIZIONE"
	FOREIGN KEY (FK_GDP_LOG_EDIZIONE) REFERENCES GDP_LOG_EDIZIONE (ID_GDP_LOG_EDIZIONE);

ALTER TABLE GDP_DATA_USCITA ADD CONSTRAINT "FK_GDP_DATA_USCITA_GDP_PERIODICITA"
	FOREIGN KEY (FK_GDP_PERIODICITA) REFERENCES GDP_PERIODICITA (ID_GDP_PERIODICITA);

ALTER TABLE GDP_EDIZIONE ADD CONSTRAINT "FK_GDP_EDIZIONE_GDP_TESTATA"
	FOREIGN KEY (FK_GDP_TESTATA) REFERENCES GDP_TESTATA (ID_GDP_TESTATA);

ALTER TABLE GDP_FASCICOLO ADD CONSTRAINT "FK_GDP_FASCICOLO_GDP_UTENTEWEB"
	FOREIGN KEY (FK_GDP_UTENTEWEB) REFERENCES GDP_UTENTEWEB (ID_GDP_UTENTEWEB);

ALTER TABLE GDP_FASCICOLO_PAG ADD CONSTRAINT "FK_GDP_FASCICOLO_PAG_GDP_FASCICOLO"
	FOREIGN KEY (FK_GDP_FASCICOLO) REFERENCES GDP_FASCICOLO (ID_GDP_FASCICOLO);

ALTER TABLE GDP_FASCICOLO_PAG ADD CONSTRAINT "FK_GDP_FASCICOLO_PAG_GDP_PAGINA"
	FOREIGN KEY (FK_GDP_PAGINA) REFERENCES GDP_PAGINA (ID_GDP_PAGINA);

ALTER TABLE GDP_LOG ADD CONSTRAINT "FK_GDP_LOG_GDP_TESTATA"
	FOREIGN KEY (FK_GDP_TESTATA) REFERENCES GDP_TESTATA (ID_GDP_TESTATA);

ALTER TABLE GDP_LOG ADD CONSTRAINT "FK_GDP_LOG_GDP_UTENTESFTP"
	FOREIGN KEY (FK_GDP_UTENTEFTP) REFERENCES GDP_UTENTESFTP (ID_GDP_UTENTESFTP);

ALTER TABLE GDP_LOG_EDIZIONE ADD CONSTRAINT "FK_GDP_LOG_EDIZIONE_GDP_EDIZIONE"
	FOREIGN KEY (FK_GDP_EDIZIONE) REFERENCES GDP_EDIZIONE (ID_GDP_EDIZIONE);

ALTER TABLE GDP_LOG_EDIZIONE ADD CONSTRAINT "FK_GDP_LOG_EDIZIONE_GDP_LOG"
	FOREIGN KEY (FK_GDP_LOG) REFERENCES GDP_LOG (ID_GDP_LOG);

ALTER TABLE GDP_LOG_EDIZIONE ADD CONSTRAINT "FK_GDP_LOG_EDIZIONE_GDP_TIPO_EDIZIONE"
	FOREIGN KEY (TIPO_EDIZIONE) REFERENCES GDP_TIPO_EDIZIONE (COD_TIPO);

ALTER TABLE GDP_PAGINA ADD CONSTRAINT "FK_GDP_PAGINA_GDP_EDIZIONE"
	FOREIGN KEY (FK_GDP_EDIZIONE) REFERENCES GDP_EDIZIONE (ID_GDP_EDIZIONE);

ALTER TABLE GDP_PAGINA ADD CONSTRAINT "FK_GDP_PAGINA_GDP_TESTATA"
	FOREIGN KEY (FK_GDP_TESTATA) REFERENCES GDP_TESTATA (ID_GDP_TESTATA);

ALTER TABLE GDP_PERIODICITA ADD CONSTRAINT "FK_GDP_PERIODICITA_GDP_TESTATA"
	FOREIGN KEY (FK_GDP_TESTATA) REFERENCES GDP_TESTATA (ID_GDP_TESTATA);

ALTER TABLE GDP_PREF_EDIZIONE ADD CONSTRAINT "FK_GDP_PREF_EDIZIONE_GDP_EDIZIONE"
	FOREIGN KEY (FK_GDP_EDIZIONE) REFERENCES GDP_EDIZIONE (ID_GDP_EDIZIONE);

ALTER TABLE GDP_PREF_EDIZIONE ADD CONSTRAINT "FK_GDP_PREF_EDIZIONE_GDP_UTENTEWEB"
	FOREIGN KEY (FK_GDP_UTENTEWEB) REFERENCES GDP_UTENTEWEB (ID_GDP_UTENTEWEB);

ALTER TABLE GDP_PREF_TESTATA ADD CONSTRAINT "FK_GDP_PREF_TESTATA_GDP_TESTATA"
	FOREIGN KEY (FK_GDP_TESTATA) REFERENCES GDP_TESTATA (ID_GDP_TESTATA);

ALTER TABLE GDP_PREF_TESTATA ADD CONSTRAINT "FK_GDP_PREF_TESTATA_GDP_UTENTEWEB"
	FOREIGN KEY (FK_GDP_UTENTEWEB) REFERENCES GDP_UTENTEWEB (ID_GDP_UTENTEWEB);

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN GDP_EDIZIONE.DATA_EDIZIONE
	IS 'è la data di uscita in edicola dell’edizione';

COMMENT ON COLUMN GDP_EDIZIONE.DATA_PUBBLICAZIONE
	IS '  >  per le edizioni attive è valorizzata con la data in cui diverrà visibile a tutti
  >  per le edizioni storiche è uguale alla data edizione';

COMMENT ON COLUMN GDP_FASCICOLO.NOTE_FASCICOLO
	IS 'Note inserite dall''utente sul fascicolo';

COMMENT ON COLUMN GDP_FASCICOLO_PAG.FK_GDP_PAGINA
	IS 'riferimento alla pagina inserita nel fascicolo';

COMMENT ON COLUMN GDP_FASCICOLO_PAG.NOTE_PAGINA
	IS 'Note inserite dall''utente sulla PAGINA';

COMMENT ON COLUMN GDP_FASCICOLO_PAG.POSIZIONE
	IS 'Posizione ordinale della pagina all''interno del fascicolo (modificabile dall''utente)';

COMMENT ON COLUMN GDP_LOG.TIPO_ACQUISIZIONE
	IS 'G = giornaliera
S = storica';

COMMENT ON COLUMN GDP_LOG.DT_ACQUISIZIONE
	IS 'E'' la data della trasmissione FTP nel formato yyyy-mm-dd HH:MM:SS ricavata dalla creazione dei file';

COMMENT ON COLUMN GDP_LOG.TOTALE_FILE_ACQUISITI
	IS 'Totale numero file presenti in area ftp';

COMMENT ON COLUMN GDP_LOG.ESITO
	IS 'msg valorizzatI a seguito della chiusura complessiva del processo';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.NRO_PAG_ACQUISITE
	IS 'file PDF dell''edizione acquisiti in area ftp';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.TIPO_EDIZIONE
	IS 'decodificato su GDP_TIPO_EDIZIONE';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.NRO_PAG_VALIDE
	IS 'file PDF che sono stati correttamente registrati su DB e trasmessi al DAM';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.NRO_PAG_ERRATE
	IS 'file PDF che presentano anomalia (non leggibili, nome errato,…)';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.PRIMA_PAGINA
	IS 'Indica se è presente la prima pagina (identificata attraverso il nome del file o proceura euristica)';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.FILE_XML
	IS 'Indica se il file è stato generato';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.FILE_ZIP
	IS 'Indica se il file è stato generato';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.JOB_ID
	IS 'Identificativo dell’operazione attivata sul DAM per il caricamento dell''edizione, restituito dal servizio richiamato';

COMMENT ON COLUMN GDP_LOG_EDIZIONE.DESCRIZIONE
	IS 'Eventuali dettagli su qualsiasi tipo di anomialia rilevata';

COMMENT ON COLUMN GDP_PAGINA.ANNO_EDIZIONE
	IS 'è l''anno della data di uscita in edicola dell''edizione';

COMMENT ON COLUMN GDP_PAGINA.OBLIO
	IS 'Elenco delle voci eventualemente deindicizzare.';

COMMENT ON COLUMN GDP_PAGINA.DATA_OBLIO
	IS 'Data della richiesta di deindicizzazione';

COMMENT ON COLUMN GDP_PAGINA.NOTA_OBLIO
	IS 'Contiene eventuali informazioni integrative da pubblicare relative a richieste di oblio';

COMMENT ON COLUMN GDP_PERIODICITA.GG_PERIODICITA
	IS 'Regola di calcolo
 vedi procedura “F01 - Configurazione date edizioni attese” ';

COMMENT ON COLUMN GDP_PERIODICITA.DT_FINE_VALIDITA
	IS 'è la data di fine validità della configurazione di periodicità. 
VINCOLO: un solo record con NULL';

COMMENT ON COLUMN GDP_PERIODICITA.INIZIO_SOSPENSIONE
	IS 'Se valorizzata deve esserlo anche FINE_SOSPENSIONE.
Indicano il periodo nel quale non sono attese edizioni;
quindi i corrispondenti record nella tabella DATA_USCITA devono avere SOSPESA = True';

COMMENT ON COLUMN GDP_PERIODICITA.FINE_SOSPENSIONE
	IS 'Se valorizzata deve esserlo anche INIZIO_SOSPENSIONE.
Indicano il periodo nel quale non sono attese edizioni;
quindi i corrispondenti record nella tabella DATA_USCITA devono avere SOSPESA = True';

COMMENT ON TABLE GDP_PREF_EDIZIONE
	IS 'Tabella gestita con soli INSERT e DELETE per ogni aggiunta/eliminazione di un''edizione nell''elenco preferiti';

COMMENT ON COLUMN GDP_PREF_EDIZIONE.DT_PUBBLICAZIONE
	IS 'Campo ridondato di GDP_EDIZIONE';

COMMENT ON TABLE GDP_PREF_TESTATA
	IS 'Tabella gestita con soli INSERT e DELETE per ogni aggiunta/eliminazione di una testata nell''elenco preferiti';

COMMENT ON COLUMN GDP_TESTATA.INVIO_EDIZIONE
	IS 'True = testate che inviano edizioni pediodiche
False = testate che non inviano';

COMMENT ON COLUMN GDP_TESTATA.STATO
	IS '0 = attiva
1 = storica';

COMMENT ON COLUMN GDP_TESTATA.SOC_EDITRICE
	IS 'per le testate in attività con flusso periodico';

COMMENT ON COLUMN GDP_TESTATA.ENTE_PROPONENTE
	IS 'per le testate storiche con caricamenti saltuari
Ex PRESENTATO_DA';


/* Tavole di decodifica  -  DATI */

INSERT INTO GDP_TEMA (COD_TEMA, TEMA) VALUES
	(1,'Cronaca Locale'),
	(2,'Pubblica Amministrazione'),
	(3,'Lavoro'),
	(4,'Cinema'),
	(5,'Cultura');
	 
INSERT INTO GDP_PROVINCE (SIGLA, PROVINCIA) VALUES
	('AL','Alessandria'),
	('AT','Asti'),
	('BI','Biella'),
	('CN','Cuneo'),
	('NO','Novara'),
	('TO','Torino'),
	('VB','Verbano Cusio Ossola'),
	('VC','Vercelli');

INSERT INTO GDP_TIPO_EDIZIONE (COD_TIPO, TIPO_EDIZIONE) VALUES
	('OK', 'corrispondente'),
	('SO', 'sospesa'),
	('AN', 'anticipataria'),
	('PO', 'posticipataria'),
	('AA', 'anomalia edizione attesa'),
	('ST', 'edizione storica'),
	('AS', 'edizione storica con anomalia');

INSERT INTO GDP_TIPO_FILE (COD_TIPO, TIPO_FILE) VALUES
	('NP', 'PDF multi-pagina'),
	('NL', 'file non leggibile'),
	('NF', 'file formato errato'),
	('DA', 'data attesa'),
	('PP', 'prima pagina');

INSERT INTO GDP_MAIL (COD_MAIL,SMTP_MAIL_HOST,SMTP_MAIL_PORTA,MITTENTE,TESTO_OGGETTO,TESTO_MAIL) VALUES
	('GW001','mailfarm-app.csi.it',25,'assistenza.bdp@csi.it','Giornali del Piemonte - Edizione da integrare','L''edizione del <[dataED]> della testata <[nomeTestata]> ha evidenziato le seguenti anomalie:\n\n\nSi richiede di ritrasmettere le pagine indicate'),
	('GE001','mailfarm-app.csi.it',25,'assistenza.bdp@csi.it','Giornali del Piemonte - Edizione non caricata','L''edizione del <[dataED]> della testata <[nomeTestata]> ha evidenziato errori che hanno impedito il caricamento in piattaforma.\nSi richiede di ritrasmettere l''intera edizione'),
	('SW001','mailfarm-app.csi.it',25,'assistenza.bdp@csi.it','Giornali del Piemonte - Edizione da integrare','L''edizione del <dataED> della testata storica <[nomeTestata]> ha evidenziato le seguenti anomalie:\n\n\nSi richiede di ritrasmettere le pagine indicate'),
	('SE001','mailfarm-app.csi.it',25,'assistenza.bdp@csi.it','Giornali del Piemonte - Edizione non caricata','L''edizione del <[dataED]> della testata storica <[nomeTestata]> ha evidenziato errori che hanno impedito il caricamento in piattaforma.\nSi richiede di ritrasmettere l''intera edizione'),
	('ST001','mailfarm-app.csi.it',25,'assistenza.bdp@csi.it','Giornali del Piemonte - Edizioni testata non caricate','L''edizioni della testata storica <[nomeTestata]> hanno evidenziato errori che ne hanno impedito il caricamento in piattaforma.\nSi richiede di ritrasmettere l''intero elenco di edizioni della predetta testata');
