quarkus.application.name=gdporch
quarkus.http.port=8082
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${GDP_DB_USER}
quarkus.datasource.password=${GDP_DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gdp_db
quarkus.hibernate-orm.database.generation=none
quarkus.scheduler.enabled=true
# folders 
sftp.root.prefix=flusso_regolare/
sftp.root.prefix.dam=_dam/
sftp.root.prefix.errata=_errata/
sftp.root.prefix.tmp=_tmp/
sftp.root.prefix.flussoSaltuario=flusso_saltuario/


# SFTP Configuration (Local Docker)
sftp.host=localhost
sftp.port=2222
sftp.username=tester
sftp.password=password
sftp.key.path=${SFTP_KEY}



# DAM LIBRA REST Client
libra.api.url=http://ts-libra-sv-exp1.csi.it/rpcr02
quarkus.rest-client."it.csipiemonte.gdp.gdporch.client.LibreClient".url=${libra.api.url}

# Monitoring settings
quarkus.micrometer.export.prometheus.enabled=true
quarkus.smallrye-health.root-path=/q/health



